USE PRODUCTDB

CREATE TABLE PRODUCTS 
(
PRODUCTID INT PRIMARY KEY,
PRODUCTNAME NVARCHAR(255),
CATEGORY NVARCHAR(100),
PRICE FLOAT,
RATING FLOAT,
DISCOUNT FLOAT
);

SELECT * FROM PRODUCTS

-- TOP 10 PRODUCTS BY PRICE
SELECT TOP 10 *
FROM PRODUCTS
ORDER BY PRICE DESC

-- COUNT PRODUCTS BY CATEGORY
SELECT CATEGORY, COUNT(*) AS TOTALPRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY


-- HIGHEST-RATED PRODUCTS
SELECT TOP 10 PRODUCTNAME, RATING
FROM PRODUCTS
ORDER BY RATING DESC





